name: Update Bricotop Website
on: 
    push:
        branches: [prod]
jobs:
    build-and-prepare-site:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout site code
              uses: actions/checkout@v4
            
            - name: Build site and prepare final index.html
              run: npm run build:publish

            - run: echo "I could now use the linode api to upload"
            
            - name: check build success
              run: ls -l dist
